baseURL = 'https://mastershubham.github.io/'
languageCode = 'en-us'
title = 'Project Polymath'
timeZone = 'Asia/Kolkata'

[params]
description = 'A personal publication about mathematics, computing, engineering, research, and ideas.'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'github'
lineNos = true